## static_countries
UPDATE static_countries SET cn_short_ro='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_ro='Emiratele Arabe Unite' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_ro='Afganistan' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_ro='Antigua şi Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_ro='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_ro='Albania' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_ro='Armenia' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_ro='Antilele Olandeze' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_ro='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_ro='Antarctica' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_ro='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_ro='Samoa Americană' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_ro='Austria' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_ro='Australia' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_ro='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_ro='Insulele Åland' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_ro='Azerbaidjan' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_ro='Bosnia şi Herţegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_ro='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_ro='Bangladeş' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_ro='Belgia' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_ro='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_ro='Bulgaria' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_ro='Bahrain' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_ro='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_ro='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_ro='Saint Barthélemy' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_ro='Bermuda' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_ro='Brunei Darussalam' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_ro='Bolivia' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_ro='Insulele Bonaire, Sint Eustatius și Saba' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_ro='Brazilia' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_ro='Bahamas' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_ro='Bhutan' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_ro='Insula Bouvet' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_ro='Botswana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_ro='Belarus' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_ro='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_ro='Canada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_ro='Insulele Cocos (Keeling)' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_ro='Republica Democrată Congo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_ro='Republica Centrafricană' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_ro='Congo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_ro='Elveţia' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_ro='Coasta de Fildeş' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_ro='Insulele Cook' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_ro='Chile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_ro='Camerun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_ro='China' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_ro='Columbia' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_ro='Costa Rica' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_ro='Serbia şi Muntenegru' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_ro='Cuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_ro='Republica Capului Verde' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_ro='Curaçao' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_ro='Insula Crăciun' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_ro='Cipru' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_ro='Republica Cehă' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_ro='Germania' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_ro='Djibouti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_ro='Danemarca' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_ro='Dominica' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_ro='Republica Dominicană' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_ro='Algeria' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_ro='Ecuador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_ro='Estonia' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_ro='Egipt' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_ro='Sahara Occidentală' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_ro='Eritreea' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_ro='Spania' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_ro='Etiopia' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_ro='Finlanda' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_ro='Fiji' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_ro='Insulele Falkland' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_ro='Micronezia' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_ro='Insulele Feroe' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_ro='Franţa' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_ro='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_ro='Marea Britanie' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_ro='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_ro='Georgia' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_ro='Guyana Franceză' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_ro='Guernsey' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_ro='Ghana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_ro='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_ro='Groenlanda' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_ro='Gambia' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_ro='Guineea' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_ro='Guadalupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_ro='Guineea Ecuatorială' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_ro='Grecia' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_ro='Georgia de Sud şi Insulele Sandwich de Sud' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_ro='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_ro='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_ro='Guineea Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_ro='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_ro='Hong Kong' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_ro='Insula Heard şi Insulele McDonald' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_ro='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_ro='Croaţia' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_ro='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_ro='Ungaria' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_ro='Indonezia' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_ro='Irlanda' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_ro='Israel' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_ro='Insula Man' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_ro='India' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_ro='Teritoriul Britanic din Oceanul Indian' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_ro='Irak' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_ro='Iran' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_ro='Islanda' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_ro='Italia' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_ro='Jersey' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_ro='Jamaica' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_ro='Iordania' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_ro='Japonia' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_ro='Kenya' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_ro='Kârgâzstan' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_ro='Cambodgia' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_ro='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_ro='Insulele Comore' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_ro='Sf. Kitts şi Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_ro='Republica Populară Democrată Coreeană' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_ro='Republica Coreea' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_ro='Kuweit' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_ro='Insulele Cayman' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_ro='Kazahstan' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_ro='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_ro='Liban' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_ro='Sf. Lucia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_ro='Liechtenstein' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_ro='Sri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_ro='Liberia' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_ro='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_ro='Lituania' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_ro='Luxemburg' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_ro='Letonia' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_ro='Libia' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_ro='Maroc' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_ro='Monaco' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_ro='Republica Moldova' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_ro='Muntenegru' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_ro='Sf. Martin' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_ro='Madagascar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_ro='Insulele Marshall' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_ro='Macedonia' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_ro='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_ro='Myanmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_ro='Mongolia' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_ro='Macao' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_ro='Marianele de Nord' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_ro='Martinica' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_ro='Mauritania' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_ro='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_ro='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_ro='Mauritius' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_ro='Maldive' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_ro='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_ro='Mexic' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_ro='Malaysia' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_ro='Mozambic' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_ro='Namibia' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_ro='Noua Caledonie' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_ro='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_ro='Insula Norfolk' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_ro='Nigeria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_ro='Nicaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_ro='Olanda' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_ro='Norvegia' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_ro='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_ro='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_ro='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_ro='Noua Zeelandă' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_ro='Oman' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_ro='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_ro='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_ro='Polinezia Franceză' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_ro='Papua Noua Guinee' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_ro='Filipine' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_ro='Pakistan' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_ro='Polonia' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_ro='Saint Pierre şi Michelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_ro='Pitcairn' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_ro='Puerto Rico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_ro='Palestina' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_ro='Portugalia' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_ro='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_ro='Paraguay' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_ro='Qatar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_ro='Réunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_ro='România' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_ro='Serbia' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_ro='Federaţia Rusă' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_ro='Rwanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_ro='Arabia Saudită' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_ro='Insulele Solomon' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_ro='Seychelles' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_ro='Sudan' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_ro='Suedia' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_ro='Singapore' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_ro='Sf. Elena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_ro='Slovenia' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_ro='Svalbard şi Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_ro='Slovacia' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_ro='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_ro='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_ro='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_ro='Somalia' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_ro='Suriname' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_ro='Sudanul de Sud' WHERE cn_iso_2='SS';
UPDATE static_countries SET cn_short_ro='São Tomé şi Príncipe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_ro='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_ro='Sint Maarten' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_ro='Siria' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_ro='Swaziland' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_ro='Insulele Turks şi Caicos' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_ro='Ciad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_ro='Zona Antarctică Franceză' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_ro='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_ro='Thailanda' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_ro='Tadjikistan' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_ro='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_ro='Turkmenistan' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_ro='Tunisia' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_ro='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_ro='Timorul de Est' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_ro='Turcia' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_ro='Trinidad şi Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_ro='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_ro='Taiwan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_ro='Tanzania' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_ro='Ucraina' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_ro='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_ro='Oceania Americană' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_ro='Statele Unite ale Americii' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_ro='Uruguay' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_ro='Uzbekistan' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_ro='Vatican' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_ro='Sf. Vicenţiu şi Grenadinele' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_ro='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_ro='Insulele Virgine Britanice' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_ro='Insulele Virgine Americane' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_ro='Vietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_ro='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_ro='Wallis şi Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_ro='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_ro='Kosovo' WHERE cn_iso_2='XK';
UPDATE static_countries SET cn_short_ro='Yemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_ro='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_ro='Africa de Sud' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_ro='Zambia' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_ro='Zimbabwe' WHERE cn_iso_2='ZW';

UPDATE static_countries SET cn_official_name_ro = cn_short_ro WHERE cn_official_name_ro='' OR cn_official_name_ro IS NULL;
